### PR TITLE
Add M7A Instances

### PR DESCRIPTION
**Pull request by say25**

### CODE REVIEW

**Review by nrollr — CHANGES_REQUESTED** [review]
Hi Steven, 
thank you for your contribution, much appreciated! 🤓

However before merging a couple of changes are required: 

The indexation/hash of new instance type is typically done through a small python script using the hashlib library - [there's the code](https://gist.github.com/nrollr/cb678d4220f5226ee57480fb18f4f3a4), resulting in different hashes than the ones you've included :

* m7a.medium = f9c8743301b7b523
* m7a.large = e80ac7fe3c7b8116
* m7a.xlarge = 1c59dbd65e84584c
* m7a.2xlarge = e54b93be64d71680
* m7a.4xlarge = 61ba31aad8072daf
* m7a.8xlarge = 867915be3da8d490
* m7a.12xlarge = 48d7bde58b070be7
* m7a.16xlarge = c5c29fa9a75084f9
* m7a.24xlarge = 22a5c26672ef94cf
* m7a.32xlarge = e510ac9ef0cd2426
* m7a.48xlarge = eb989336e8190de3
* m7a.metal-48xl = 4144a25cb48e034a 

Second in the index.html, the latest batch of new instance types are always featured on top, meaning instead of adding code after line 96, it should be placed after line 83 + the next block of instances requires a "mt-3" value (only the first block within the same instance category (eg. General Purpose) has a "mt-1" value.) 

Otherwise everything else is top notch ! 👍

**Comment by say25** [comment]
@nrollr I think I addressed all the feedback correctly? Its possible I didn't but trying my best here 😅 

Also added how the hashes are done to the docs for the next contributor

**Review by nrollr — APPROVED** [review]
All good !

**Comment by nrollr** [comment]
@say25 Thank you for the contribution !

**Pull request merged**
